spring:
  url: https://www.google.com
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bongsamoa_test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true